Service:
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      DeployTimeout: 7200
      SupplierTemplateConfigs:
        - Name: 模板1
          Url: ros_templates/template1.yaml
          PredefinedParameters: []
          AllowedRegions:
            - cn-qingdao
            - cn-beijing
            - cn-zhangjiakou
            - cn-huhehaote
            - cn-wulanchabu
            - cn-hangzhou
            - cn-shanghai
            - cn-hangzhou-acdr-ut-3
            - cn-shenzhen
            - cn-heyuan
            - cn-guangzhou
            - cn-wuhan-lr
            - cn-zhongwei
            - cn-chengdu
            - cn-hongkong
            - ap-northeast-1
            - ap-northeast-2
            - ap-southeast-1
            - ap-southeast-8
            - ap-southeast-3
            - ap-southeast-6
            - ap-southeast-5
            - ap-southeast-7
            - us-east-1
            - us-west-1
            - us-southeast-1
            - na-south-1
            - eu-west-1
            - eu-west-2
            - me-east-1
            - me-central-1
            - eu-central-1
    TemplateConfigs:
      - Name: 模板1
        Url: 
          https://service-info-private.oss-cn-hangzhou.aliyuncs.com/1853370294850618/template/templateConfig-f2073c42-6468-419c-8915-c843328f6a67.json?Expires=1782368649&OSSAccessKeyId=LTAI5tCYphFhocJemeMWmXst&Signature=jt%2B7osu6UV2IK6mwWWphxhPCW7Y%3D
        AllowedRegions:
          - cn-qingdao
          - cn-beijing
          - cn-zhangjiakou
          - cn-huhehaote
          - cn-wulanchabu
          - cn-hangzhou
          - cn-shanghai
          - cn-hangzhou-acdr-ut-3
          - cn-shenzhen
          - cn-heyuan
          - cn-guangzhou
          - cn-wuhan-lr
          - cn-zhongwei
          - cn-chengdu
          - cn-hongkong
          - ap-northeast-1
          - ap-northeast-2
          - ap-southeast-1
          - ap-southeast-8
          - ap-southeast-3
          - ap-southeast-6
          - ap-southeast-5
          - ap-southeast-7
          - us-east-1
          - us-west-1
          - us-southeast-1
          - na-south-1
          - eu-west-1
          - eu-west-2
          - me-east-1
          - me-central-1
          - eu-central-1
        PredefinedParameters: []
        DeployScene: ECS
        OutputConfigs:
          - OutputKey: QoderWake Private Addresses
            EnableWebProxy: true
    NetworkMetadata:
      EnablePrivateVpcConnection: false
      EnableReversePrivateVpcConnection: false
    ServiceInstanceNameRule:
      Prefix: QoderWake-
      UseDefaultValue: true
  OperationMetadata:
    SupportBackup: false
    PrometheusConfigMap:
      模板1:
        EnablePrometheus: false
  ServiceType: private
  ServiceInfo:
    - Agreements: []
      Image: resources/icons/service_logo_zh-CN.png
      Locale: zh-CN
      Name: QoderWake
      ShortDescription: "QoderWake 让你在本机组建一支”数字员工”团队（Wakers）。每个员工有岗位、有名字、有人设、有专长，可以被你召唤聊天或干活，也可以按计划或事件自动开工。他们能做什么、用什么工具、有什么记忆、能碰什么不能碰什么——全部可配。\n"
      Softwares: []
  ShareType: Public
  ApprovalType: Manual
Artifact: {}
